// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNiGouhzzZSJ0q2gKgJ2mK2brSSuRxfKk',
    appId: '1:552811546534:web:b1273e155d12dee633b167',
    messagingSenderId: '552811546534',
    projectId: 'oncovault-8cbbc',
    authDomain: 'oncovault-8cbbc.firebaseapp.com',
    storageBucket: 'oncovault-8cbbc.firebasestorage.app',
    measurementId: 'G-3G679P4KDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhhatW0IlF7IxLYr68u4gq64YiIwDyfAY',
    appId: '1:552811546534:android:e8d905cc086084cc33b167',
    messagingSenderId: '552811546534',
    projectId: 'oncovault-8cbbc',
    storageBucket: 'oncovault-8cbbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCia8C5fATAeGXugsvc7XY12RMXltMP8GQ',
    appId: '1:552811546534:ios:fea493a7f1a78c3e33b167',
    messagingSenderId: '552811546534',
    projectId: 'oncovault-8cbbc',
    storageBucket: 'oncovault-8cbbc.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCia8C5fATAeGXugsvc7XY12RMXltMP8GQ',
    appId: '1:552811546534:ios:fea493a7f1a78c3e33b167',
    messagingSenderId: '552811546534',
    projectId: 'oncovault-8cbbc',
    storageBucket: 'oncovault-8cbbc.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNiGouhzzZSJ0q2gKgJ2mK2brSSuRxfKk',
    appId: '1:552811546534:web:8c6df0f149b1ee5e33b167',
    messagingSenderId: '552811546534',
    projectId: 'oncovault-8cbbc',
    authDomain: 'oncovault-8cbbc.firebaseapp.com',
    storageBucket: 'oncovault-8cbbc.firebasestorage.app',
    measurementId: 'G-XZ6PG7CTKG',
  );
}
